#!/usr/bin/env python3
"""Create Abyss Road Ep1 project and run full pipeline."""
import requests, json, time, sys

BASE = "http://localhost:7862"

ASSETS = [
    {"name": "卡洛斯_门德斯", "type": "角色", "prompt": "Split composition character reference board, left side extreme close-up portrait, right side three-view turnaround. Left: weathered Portuguese captain, mid-40s, salt-and-pepper short hair, deep-set dark eyes, sun-weathered olive skin, trimmed grey beard, scar across left cheekbone, wearing dark navy 17th century captain coat with gold buttons, white cravat, leather belt with brass buckle. Right: full body standing in captain attire, confident stance. Professional reference sheet layout, neutral grey background, even lighting.", "is_primary": True},
    {"name": "伊莎贝拉_桑托斯", "type": "角色", "prompt": "Split composition character reference board, left side extreme close-up portrait, right side three-view turnaround. Left: young Portuguese woman, early 30s, dark auburn hair in loose braid over shoulder, sharp green eyes, high cheekbones, light freckles across nose, wearing simple white linen shirt under brown leather vest, silver cross necklace. Right: full body standing, hands on hips, wearing explorer clothing with leather satchel. Professional reference sheet layout, neutral grey background, even lighting.", "is_primary": True},
    {"name": "费尔南多_罗查", "type": "角色", "prompt": "Split composition character reference board, left side extreme close-up portrait, right side three-view turnaround. Left: Portuguese first mate, late 30s, bald head, thick black eyebrows, warm brown eyes, stocky build, wearing simple white sailor shirt, red sash around waist, compass on leather cord around neck. Right: full body standing, arms crossed, sailor attire. Professional reference sheet layout, neutral grey background, even lighting.", "is_primary": True},
    {"name": "海妖号_帆船", "type": "场景", "prompt": "17th century Portuguese caravel sailing ship, three masts with square sails, dark oak hull with brass fittings, ornate figurehead of a sea serpent, lanterns hanging from rigging, ship name Sereia painted on stern in gold. Night scene with starlight, gentle ocean waves. Cinematic wide shot, atmospheric fog, moonlight silver on water. Professional reference, clean layout.", "is_primary": True},
    {"name": "迷雾海面", "type": "场景", "prompt": "Vast dark ocean surface covered in thick unnatural green-tinted fog, no horizon visible, fog swirling in spiraling patterns, bioluminescent blue-green lights flickering beneath the water surface, dead calm water reflecting nothing. Eerie atmospheric scene, 17th century nautical setting. Professional reference, clean layout.", "is_primary": True},
    {"name": "石质祭坛岛屿", "type": "场景", "prompt": "Small volcanic island, black basalt rock formations, ancient stone pillars arranged in circle on a flat plateau, carved with spiral and tentacle patterns, moss and lichen covering lower portions, narrow path leading from rocky shore to plateau, crashing dark waves below. Overcast sky with green-tinted clouds. Professional reference, clean layout.", "is_primary": True},
    {"name": "地下神殿", "type": "场景", "prompt": "Vast underground cavern with vaulted ceiling, walls covered in bioluminescent blue-green fungus, central stone altar with carved tentacle reliefs, shallow pool of dark water surrounding altar, ancient chains hanging from ceiling, stone steps leading down from entrance. Dim blue-green lighting, mist hovering over water. Professional reference, clean layout.", "is_primary": True},
    {"name": "古老石碑", "type": "道具", "prompt": "Ancient stone tablet, approximately 1 meter tall, covered in carved symbols mixing Portuguese and unknown geometric patterns, surface cracked and weathered, faint blue-green luminescence emanating from carved grooves, propped against stone wall. Professional reference, clean layout.", "is_primary": True},
    {"name": "深海护符", "type": "道具", "prompt": "Small oval amulet made of dark green stone with gold wire wrapping, center contains a polished black pearl that seems to shift with internal light, chain of tarnished silver links, ancient Portuguese inscription on back. Professional reference, clean layout, neutral background.", "is_primary": True},
    {"name": "船长舱室", "type": "场景", "prompt": "Interior of 17th century ship captain cabin, dark wood paneling, nautical charts on walls, brass lantern on desk casting warm light, log book open on desk, compass and astrolabe on shelf, narrow bed with wool blanket, porthole showing dark sea outside. Warm amber lighting, shadows in corners. Professional reference, clean layout.", "is_primary": True},
]

SEGMENTS = [
    {"id":1,"title":"开头钩子 - 日志最后一页","assets":["卡洛斯_门德斯","船长舱室"],"shots":[{"time":"0s-3s","type":"ECU","camera":"locked-off, slow push in","visual":"Extreme close-up of a weathered ship log book, last page. Handwritten Portuguese text fades mid-sentence. The final words read 'It is watching us now.' A drop of seawater falls onto the page, blurring the ink. The handwriting becomes increasingly frantic toward the bottom.","lighting":"Single brass lantern, warm amber 2700K, flickering shadows on parchment","dialogue":"","audio":"Faint creak of ship timbers, water dripping, distant wind howling","transition":"[cut]"},{"time":"3s-6s","type":"CU","camera":"slow tilt up from log book","visual":"Camera tilts up from the log book to reveal Captain Carlos sitting at his desk, head in hands. His captain coat hangs loosely. The lantern flame bends as if pushed by an unseen force. Through the porthole behind him, the sea is unnaturally still and dark.","lighting":"Warm lantern light on desk, cold blue-green from porthole, strong contrast","dialogue":"Carlos (voiceover, exhausted): Three days since the fog closed in. Three days since we lost sight of the stars.","audio":"Lantern flame sputtering, ship groaning, distant low hum from outside","transition":"[cut]"},{"time":"6s-10s","type":"WS","camera":"slow dolly back through cabin door","visual":"Camera pulls back through the cabin doorway revealing the ship deck. An unnatural green-tinted fog surrounds the ship completely. No horizon, no stars, no moon. The fog pulses faintly with bioluminescent blue-green light from below the waterline. Sailors move nervously on deck, lanterns in hand.","lighting":"Ship lanterns warm orange vs surrounding fog cold blue-green, extreme contrast","dialogue":"","audio":"Wind dies to silence, then a deep resonant tone from beneath the water, rigging creaks","transition":"[cut]"}]},
    {"id":2,"title":"迷雾中的信号","assets":["海妖号_帆船","迷雾海面"],"shots":[{"time":"0s-4s","type":"WS","camera":"crane shot rising above ship","visual":"Aerial view of the caravel surrounded by swirling green fog. The fog forms slow spiral patterns around the ship. Bioluminescent lights pulse beneath the water surface in rhythmic patterns, like a heartbeat. The ship appears tiny and isolated in the vast fog ocean.","lighting":"Overhead fog diffuses all light, green tint everywhere, bioluminescent blue-green pulses from below","dialogue":"","audio":"Deep underwater pulse, fog swirling, distant whale-like moan","transition":"[cut]"},{"time":"4s-7s","type":"MS","camera":"handheld, following Isabella","visual":"Isabella stands at the bow rail, holding the deep sea amulet. The black pearl in the amulet glows faintly, pulsing in sync with the underwater lights. She stares into the fog ahead, her expression shifting from curiosity to unease. The amulet chain tenses as if pulled toward something.","lighting":"Amulet emits soft blue-green glow on her face, fog backlighting creates silhouette edges","dialogue":"Isabella (whispered): The amulet... it is resonating with something. Something ahead.","audio":"Amulet humming softly, water lapping against hull, Isabella's breath","transition":"[cut]"},{"time":"7s-10s","type":"MS","camera":"whip pan to starboard","visual":"Through the fog on the starboard side, a dark shape emerges. A small volcanic island, black basalt formations jutting from the sea. Green-tinged clouds hang above it. Ancient stone pillars are barely visible on the plateau. The fog seems to part just enough to reveal the island, as if intentionally.","lighting":"Island lit by eerie green cloud-filtered light, fog creates depth layers, no warm tones","dialogue":"Fernando (shouting from behind): Land! Captain, land off starboard!","audio":"Fog parting with a soft whoosh, waves crashing on rocks, seagulls absent","transition":"[cut]"}]},
    {"id":3,"title":"登陆黑色岛屿","assets":["卡洛斯_门德斯","伊莎贝拉_桑托斯","费尔南多_罗查","石质祭坛岛屿"],"shots":[{"time":"0s-4s","type":"MS","camera":"tracking shot from boat","visual":"A small rowboat approaches the rocky shore. Carlos at the oars, Isabella in the bow holding the amulet forward like a compass, Fernando behind scanning the cliffs. Black basalt rocks glisten with spray. The landing party steps onto the narrow rocky beach. No sand, only black stone.","lighting":"Overcast green-tinted sky, no direct sun, diffuse cold light, wet rocks reflect ambient green","dialogue":"Carlos (commanding): Stay close. We take what we need and leave.","audio":"Oars dipping in water, boots on wet rock, waves echoing off cliff face","transition":"[cut]"},{"time":"4s-7s","type":"WS","camera":"slow push in toward plateau","visual":"The three explorers climb a narrow stone path up the cliff face. Above them, the circle of ancient stone pillars becomes clearer. Each pillar is carved with spiral patterns and tentacle motifs. Moss and lichen cover the lower portions in unnatural blue-green hues.","lighting":"Cliff face in shadow, green sky above, bioluminescent lichen provides faint blue-green accents","dialogue":"","audio":"Wind picking up, stone fragments clattering under boots, low drone building","transition":"[cut]"},{"time":"7s-10s","type":"MS","camera":"low angle looking up at pillars","visual":"They reach the plateau. The stone pillars form a perfect circle, each one carved with intricate tentacle reliefs. In the center, a stone staircase descends into darkness. Isabella's amulet glows brighter, the black pearl now emitting visible blue-green light that illuminates the carved symbols on the nearest pillar.","lighting":"Amulet blue-green glow as key light, overcast green sky above, deep shadow in the staircase","dialogue":"Isabella (awed, uneasy): These carvings... they are not Portuguese. Not any language I know. But the amulet can read them.","audio":"Amulet humming louder, wind dying to stillness, a faint whispering from the staircase","transition":"[cut]"}]},
    {"id":4,"title":"石碑与预言","assets":["伊莎贝拉_桑托斯","古老石碑","石质祭坛岛屿"],"shots":[{"time":"0s-4s","type":"CU","camera":"slow orbit around stone tablet","visual":"Close-up of the ancient stone tablet propped against a pillar. Carved symbols mix recognizable Portuguese letters with unknown geometric spirals. The amulet's glow causes the carved grooves to illuminate from within, the blue-green light traveling along the patterns like veins.","lighting":"Amulet blue-green light tracing the carvings, deep shadow elsewhere, dramatic chiaroscuro","dialogue":"Isabella (reading, voice trembling): When the sea forgets its boundary... when the deep one stirs in dreaming... the gate shall open and the tide shall rise forever.","audio":"Stone vibrating with low frequency, amulet resonance, wind stops completely","transition":"[cut]"},{"time":"4s-7s","type":"MS","camera":"over-shoulder from Isabella","visual":"Isabella traces the symbols with her fingers. Behind her, Carlos and Fernando exchange worried glances. Fernando fingers the compass at his chest, but the compass needle spins wildly. Carlos grips the hilt of his cutlass.","lighting":"Amulet glow as key light on tablet and Isabella, green overcast ambient on the men","dialogue":"Fernando (nervous): Captain, the compass has gone mad. We should go back to the ship.","audio":"Compass clicking as it spins, distant rumble from underground, Isabella's breathing","transition":"[cut]"},{"time":"7s-10s","type":"WS","camera":"slow pull back revealing scale","visual":"Wide shot revealing the full circle of pillars, the three explorers small in the center. The staircase opening glows faintly from below. The carved tentacle patterns on all pillars begin to glow simultaneously with blue-green light, pulsing in unison like a heartbeat.","lighting":"All pillars now emitting blue-green pulse, fog reflecting the glow, sky darkening further","dialogue":"Carlos (resolute): We did not sail across the Atlantic to turn back at the door. We go down.","audio":"Deep resonant tone from underground, all pillars humming in unison, fog pressing inward","transition":"[cut]"}]},
    {"id":5,"title":"深入地下","assets":["卡洛斯_门德斯","伊莎贝拉_桑托斯","费尔南多_罗查","地下神殿"],"shots":[{"time":"0s-4s","type":"MS","camera":"tracking shot descending stairs","visual":"The three descend the stone staircase into the underground cavern. Bioluminescent fungus on the walls casts blue-green light. The stairs are slick with moisture. Water drips from the ceiling. The space opens up as they go deeper, revealing a vast cavern with a vaulted ceiling. Chains hang from above, swaying without wind.","lighting":"Bioluminescent blue-green fungus as primary light source, no warm tones, deep shadows beyond fungus patches","dialogue":"","audio":"Footsteps on wet stone, water dripping echoing, chains creaking, deep silence beneath","transition":"[cut]"},{"time":"4s-7s","type":"WS","camera":"crane shot revealing cavern","visual":"The full underground temple is revealed. A central stone altar surrounded by shallow dark water. Tentacle reliefs cover every surface. The fungus grows in patterns that seem deliberate, forming spiraling designs on the walls. The three explorers stand at the base of the stairs, dwarfed by the scale of the space.","lighting":"Fungus patches creating pools of blue-green light, altar in relative shadow, water reflecting ceiling darkness","dialogue":"Isabella (whispered): My God. This place is ancient. Older than Portugal itself.","audio":"Vast space echo, water lapping gently, a low hum that seems to come from the altar itself","transition":"[cut]"},{"time":"7s-10s","type":"CU","camera":"slow push toward altar","visual":"Close-up of the stone altar surface. The tentacle carvings are incredibly detailed. In the center of the altar, a hand-shaped depression, sized for the amulet. The amulet around Isabella's neck pulls forward slightly, the chain going taut.","lighting":"Fungus light from sides, amulet beginning to glow brighter casting sharp shadows on altar","dialogue":"Isabella (realizing): It was made for this. The amulet... it was meant to be placed here.","audio":"Amulet humming intensifying, stone altar vibrating with low frequency, water in pool beginning to ripple","transition":"[cut]"}]},
    {"id":6,"title":"祭坛觉醒","assets":["伊莎贝拉_桑托斯","深海护符","地下神殿"],"shots":[{"time":"0s-4s","type":"CU","camera":"locked-off on altar depression","visual":"Isabella's hand places the amulet into the altar depression. The fit is perfect. The moment contact is made, blue-green light erupts from the altar, racing along the carved channels like circuitry powering on. The light travels from the altar outward across the floor, up the walls, along the ceiling chains. The entire cavern illuminates in pulsing blue-green light.","lighting":"Explosive blue-green light from altar, then pulsing rhythmically, all fungus dims in response","dialogue":"","audio":"Sharp crack of energy, then deep resonant hum building, water in pool begins to swirl","transition":"[cut]"},{"time":"4s-7s","type":"MS","camera":"handheld, reacting with characters","visual":"Carlos grabs Isabella's arm pulling her back from the altar. Fernando stumbles backward toward the stairs. The shallow pool around the altar begins to swirl, forming a vortex. The water glows brighter from within. The chains above swing wildly.","lighting":"Pulsing blue-green from altar and water, shadows moving rapidly, dramatic strobing effect","dialogue":"Carlos (shouting): Get back! Everyone get back from the water!","audio":"Water swirling louder, chains crashing, stone grinding, deep hum reaching painful frequency","transition":"[cut]"},{"time":"7s-10s","type":"WS","camera":"crane rising, looking down at altar","visual":"From above, the pool has become a perfect glowing spiral of blue-green water. The light from the altar shoots upward in a concentrated beam, hitting the cavern ceiling. The ceiling begins to crack. Through the cracks, not sky, but darkness, deeper than any night. Something vast moves in that darkness above, just beyond perception.","lighting":"Intense blue-green beam from altar, ceiling crack revealing absolute darkness, contrast extreme","dialogue":"","audio":"Massive stone cracking, then the sound: a deep, resonant, alien song that vibrates the chest, water now churning","transition":"[cut]"}]},
    {"id":7,"title":"深渊凝视","assets":["卡洛斯_门德斯","伊莎贝拉_桑托斯","地下神殿"],"shots":[{"time":"0s-4s","type":"ECU","camera":"extreme slow push on Isabella's face","visual":"Extreme close-up of Isabella's face. Her green eyes reflect the blue-green light from below. Her pupils dilate impossibly wide. In her eyes, a reflection: something vast and coiled moving in deep water. Her expression shifts from fear to recognition, as if she has seen this before, in dreams. Tears stream down her face but she cannot look away.","lighting":"Blue-green light from below casting upward shadows, her face half in light half in shadow","dialogue":"Isabella (trance-like, barely audible): It has been waiting. For so long. It remembers everything the sea has forgotten.","audio":"Alien song continuing, her heartbeat audible, water churning below, absolute silence between pulses","transition":"[cut]"},{"time":"4s-7s","type":"MS","camera":"whip pan to ceiling crack","visual":"The ceiling crack widens. Through it, a massive shape descends, visible only as a silhouette against the blue-green glow. Enormous, coiled, covered in bioluminescent patterns. It does not fully enter the cavern, just the edge of its form. The temperature drops visibly as frost forms on the stone walls.","lighting":"Blue-green glow from below silhouetting the shape, frost catching light on walls, steam rising from pool","dialogue":"Carlos (pulling Isabella): We are leaving. NOW.","audio":"Ice cracking on stone, the alien song reaching a crescendo, then abruptly cutting to silence","transition":"[cut]"},{"time":"7s-10s","type":"WS","camera":"tracking shot following retreat","visual":"The three scramble up the stone stairs. Behind them, the pool has calmed to glassy stillness. The amulet remains on the altar, now fully illuminated, the black pearl cracked open, revealing an inner glow like a dying star. The shape in the ceiling has retreated, but the crack remains, and through it, one enormous eye, amber with a vertical slit, watches them leave. It blinks once, slowly.","lighting":"Calm blue-green after the storm, altar glowing steadily, the eye catching and reflecting light","dialogue":"","audio":"Footsteps running up stairs, single slow blink sound, then silence so complete it rings","transition":"[cut]"}]},
    {"id":8,"title":"逃离岛屿","assets":["卡洛斯_门德斯","费尔南多_罗查","海妖号_帆船","石质祭坛岛屿"],"shots":[{"time":"0s-4s","type":"MS","camera":"tracking shot running across plateau","visual":"Carlos and Fernando half-carry a dazed Isabella across the stone pillar circle. The pillars no longer glow. The fog has thickened to near opacity. They stumble down the narrow path. Behind them, from the staircase entrance, a slow blue-green light begins to pulse again.","lighting":"Fog diffusing all light, occasional blue-green pulse from behind, lanterns from the rowboat ahead","dialogue":"Fernando (panting): The ship, we need to get to the ship before the fog closes in completely!","audio":"Running footsteps, labored breathing, island vibrating with deep bass tone, fog swirling","transition":"[cut]"},{"time":"4s-7s","type":"WS","camera":"crane shot of boat and ship","visual":"The rowboat pulls away from the island shore. Behind them, the island is barely visible through the fog. The stone pillars on the plateau glow once, briefly, like eyes closing. The fog begins to close the gap between island and ship, as if trying to trap them between. The caravel's lanterns are their only guide through the fog.","lighting":"Ship lanterns warm orange in the distance, fog cold blue-green, island dark silhouette with final glow","dialogue":"","audio":"Oars splashing urgently, fog pressing in with audible density, ship bell ringing in distance","transition":"[cut]"},{"time":"7s-10s","type":"MS","camera":"from ship deck, looking back","visual":"They reach the ship and collapse on deck. Carlos looks back toward the island. The fog has completely swallowed it. No island visible. No pillars. No light. Only fog. But the fog is moving now, drifting, following the ship. The underwater bioluminescent pulses resume beneath the hull, matching the rhythm of a heartbeat.","lighting":"Deck lanterns warm, surrounding fog cold blue-green, underwater glow from below waterline","dialogue":"Carlos (quiet, to himself): We woke something up. And it is not going back to sleep.","audio":"Ship groaning, fog settling around hull, underwater pulse resuming, crew murmuring in fear","transition":"[cut]"}]},
    {"id":9,"title":"船上的异变","assets":["海妖号_帆船","费尔南多_罗查","迷雾海面"],"shots":[{"time":"0s-4s","type":"MS","camera":"handheld on deck, night","visual":"Night on the ship deck. The fog has surrounded them completely. Fernando walks the deck checking ropes. He stops. On the main mast, blue-green luminescent patterns are growing along the wood grain, like the carvings in the temple. He touches the wood. It is warm. The patterns pulse once under his fingers. He pulls his hand back sharply.","lighting":"Lantern light warm, mast patterns blue-green pulsing, fog creating soft edges on everything","dialogue":"Fernando (alarmed): Captain! The mast... it is growing something. Like the temple carvings!","audio":"Wood creaking with unusual resonance, pattern pulsing with soft hum, fog pressing against ship","transition":"[cut]"},{"time":"4s-7s","type":"CU","camera":"slow push on hull below waterline","visual":"Camera looks over the ship rail down at the waterline. Below the water, the hull is covered in the same bioluminescent patterns. They spread across the wood like roots, growing slowly but visibly. Small tendrils of blue-green light extend from the hull into the water, connecting the ship to the deep.","lighting":"Bioluminescent patterns as only light source in this shot, dark water beyond, fog above","dialogue":"","audio":"Water lapping against hull with unusual softness, patterns humming, wood groaning","transition":"[cut]"},{"time":"7s-10s","type":"MS","camera":"dolly toward Isabella in cabin","visual":"Isabella sits in the captain's cabin, staring at her hands. Where the amulet rested against her chest, a faint blue-green pattern has appeared on her skin, matching the temple carvings. She touches the pattern and it pulses. Her eyes flash briefly with the same blue-green light. She looks up at the porthole, and beyond the glass, in the fog, something vast shifts.","lighting":"Cabin lantern warm, but her skin pattern glowing blue-green, porthole showing fog with moving shadows","dialogue":"Isabella (to herself, scared but resolute): I can hear it. It is calling us deeper. And part of me... wants to follow.","audio":"Her heartbeat syncing with underwater pulse, fog pressing against porthole glass, distant alien song","transition":"[cut]"}]},
    {"id":10,"title":"火攻与挣扎","assets":["卡洛斯_门德斯","海妖号_帆船","迷雾海面"],"shots":[{"time":"0s-4s","type":"MS","camera":"handheld, urgent movement","visual":"Carlos on deck, torch in hand. He orders sailors to burn the growth off the mast. A sailor touches a torch to the blue-green patterns on the mast. The patterns recoil from the flame, shrinking back. But where they retreat, they leave blackened grooves in the wood. The ship shudders as if in pain.","lighting":"Torch flames warm orange vs blue-green patterns, dramatic contrast, smoke mixing with fog","dialogue":"Carlos (commanding): Burn it off! Every mark, every growth! This ship is still ours!","audio":"Fire crackling, wood sizzling, ship groaning loudly, crew shouting, patterns making a hissing sound","transition":"[cut]"},{"time":"4s-7s","type":"WS","camera":"pulling back from ship","visual":"The ship in the fog, multiple points of flame on deck as crew fights the growth. The fog around the ship begins to churn violently. The underwater bioluminescent pulses accelerate. The fog itself seems to push back against the flames, dampening them. The fire on the mast sputters and dims.","lighting":"Flames fighting against blue-green fog glow, fire losing ground, shadows lengthening","dialogue":"","audio":"Fire sputtering, fog pressing with audible force, underwater pulse accelerating, crew panic rising","transition":"[cut]"},{"time":"7s-10s","type":"CU","camera":"slow push on Carlos's face","visual":"Close-up of Carlos's face illuminated by the dying torch flame. The blue-green light from below is growing stronger, casting his face in alternating warm and cold light. His jaw is set. But in the reflection of his eyes, the fog has parted slightly, and far ahead, a distant green glow on the horizon. Not an island. Something larger. Much larger.","lighting":"Dying torch warm orange on one side, rising blue-green on the other, his face the battleground","dialogue":"Carlos (quiet, seeing the glow): Dear God. That is not an island.","audio":"Torch dying with a hiss, deep pulse growing louder, a new sound: massive displacement of water ahead","transition":"[cut]"}]},
    {"id":11,"title":"深渊显现","assets":["海妖号_帆船","迷雾海面"],"shots":[{"time":"0s-4s","type":"WS","camera":"extreme slow push toward horizon glow","visual":"The fog parts ahead of the ship like a curtain being drawn. Beyond it, the ocean surface stretches toward a vast green glow on the horizon. But it is not a glow on the water. It is the water itself, illuminated from below by something impossibly large. The glow extends across the entire horizon. The ship drifts toward it, the current pulling them forward against their will.","lighting":"Green horizon glow dominating, ship lanterns insignificant, fog retreating to reveal scale","dialogue":"","audio":"Current pulling water with increasing force, ship creaking under strain, the alien song returning louder","transition":"[cut]"},{"time":"4s-7s","type":"MS","camera":"from ship bow, looking down at water","visual":"Looking over the bow, the water below is no longer dark. It glows with intricate patterns, the same tentacle and spiral motifs from the temple, but scaled to the size of the ocean. The patterns stretch in every direction, converging ahead toward the horizon glow. The ship is sailing along a path laid out for it.","lighting":"Water patterns glowing blue-green, ship hull dark silhouette above, horizon green ahead","dialogue":"Isabella (from behind, calm but distant): It is a road. It wants us to follow the road.","audio":"Water flowing with purpose, patterns humming in harmony, ship moving faster than wind should carry it","transition":"[cut]"},{"time":"7s-10s","type":"ECU","camera":"locked-off on compass","visual":"Extreme close-up of Fernando's compass on deck. The needle, which had been spinning wildly, now points firmly ahead toward the green glow. It does not waver. It does not point north. It points toward whatever is waiting. The compass glass begins to frost from the inside. The needle is carved with tiny symbols that were not there before.","lighting":"Compass lit by green glow from ahead, frost catching light, needle steady and certain","dialogue":"","audio":"Compass clicking once as needle locks, frost crackling softly, then silence, then the alien song, close now","transition":"[cut]"}]},
    {"id":12,"title":"结尾钩子 - 深渊之路","assets":["海妖号_帆船","迷雾海面","伊莎贝拉_桑托斯"],"shots":[{"time":"0s-4s","type":"WS","camera":"crane shot rising above ship","visual":"The ship sails forward into the green-lit channel. The fog has fully retreated, replaced by the vast bioluminescent ocean. The horizon glow intensifies. As the camera rises, the scale becomes clear: the glowing patterns in the water form a single massive spiral, and at its center, the green glow pulses like a heart. The ship is a speck on the spiral's arm, being drawn toward the center.","lighting":"Bioluminescent ocean patterns as primary light, green horizon glow intensifying, ship tiny and dark","dialogue":"","audio":"Alien song at full volume now, harmonic and terrible, ocean current rushing, ship groaning under speed","transition":"[cut]"},{"time":"4s-7s","type":"CU","camera":"slow push on Isabella at the bow","visual":"Isabella stands at the bow, wind in her hair, the blue-green pattern on her chest glowing through her shirt. She does not look afraid anymore. She looks like someone who has accepted a destiny. Her eyes reflect the green glow ahead. She reaches out her hand toward the horizon. Behind her, Carlos watches, hand on his cutlass, unable to stop what has begun.","lighting":"Green glow from ahead lighting her face, pattern on chest pulsing, wind and spray","dialogue":"Isabella (voiceover, calm and clear): We thought we discovered the unknown. But the unknown was waiting for us. And now, there is no turning back.","audio":"Wind howling, alien song harmonizing with her voice, ship speeding through water, then everything cuts","transition":"[hard cut to black]"},{"time":"7s-10s","type":"ECU","camera":"locked-off, black screen","visual":"Black screen. Two seconds of silence. Then: a single amber eye with vertical slit opens in the darkness. The same eye from the temple ceiling. It fills the screen. It blinks once. Then text appears: THE ABYSS ROAD - Episode II. The eye remains, watching, as the text fades. Then black.","lighting":"Pure black, then amber eye glow, then black","dialogue":"","audio":"Two seconds of absolute silence. Then a single slow heartbeat. The eye opens. One blink. Silence. Title card appears with deep resonant tone. End.","transition":"[fade to black]"}]},
]

def main():
    # Login
    r = requests.post(f"{BASE}/api/auth/login", json={"email": "test@test.com", "password": "test123"})
    if r.status_code != 200:
        print("Login failed:", r.status_code, r.text[:200])
        return
    token = r.json().get("token") or r.json().get("access_token")
    print("Login OK")

    headers = {"Authorization": f"Bearer {token}"}

    # Create project with script
    script_json = {"segments": SEGMENTS, "assets": ASSETS}
    r = requests.post(f"{BASE}/api/project/create", headers=headers, json={
        "name": "深渊之航 Ep1 - 2min",
        "script": json.dumps(script_json, ensure_ascii=False),
        "raw_script": "2min Cthulhu x Age of Sail: The Abyss Road Ep1. 12 segments x 10s. Opening hook: ship log 'It is watching us now'. Ending hook: abyss eye opens, Ep2 tease.",
        "video_model": "Gemini Omni",
        "image_model": "GPT-Image2",
        "ratio": "9:16",
        "resolution": "720p",
        "duration": 10
    })
    print("Create project:", r.status_code, r.text[:300])
    proj = r.json()
    pid = proj.get("id")
    if not pid:
        print("Failed to create project!")
        return
    print(f"Project ID: {pid}, Segments: {proj.get('segments')}, Assets: {proj.get('assets')}")

    # Phase 2: Generate assets
    print("\n=== Phase 2: Generating Assets ===")
    for i in range(len(ASSETS)):
        r = requests.post(f"{BASE}/api/project/{pid}/asset/{i}/generate", headers=headers)
        print(f"  Asset {i} ({ASSETS[i]['name']}): {r.status_code}")
        time.sleep(1)

    # Wait for assets
    print("Waiting 90s for assets...")
    time.sleep(90)

    # Check asset status
    r = requests.get(f"{BASE}/api/project/{pid}", headers=headers)
    proj_data = r.json()
    assets_data = proj_data.get("assets", [])
    done = sum(1 for a in assets_data if a.get("result_url"))
    print(f"Assets done: {done}/{len(assets_data)}")

    # Phase 3: Generate storyboards
    print("\n=== Phase 3: Generating Storyboards ===")
    for i in range(len(SEGMENTS)):
        r = requests.post(f"{BASE}/api/project/{pid}/segment/{i}/generate-storyboard", headers=headers)
        print(f"  Segment {i} ({SEGMENTS[i]['title']}): {r.status_code}")
        time.sleep(1)

    # Wait for storyboards
    print("Waiting 120s for storyboards...")
    time.sleep(120)

    # Phase 4: Generate videos
    print("\n=== Phase 4: Generating Videos ===")
    for i in range(len(SEGMENTS)):
        r = requests.post(f"{BASE}/api/project/{pid}/segment/{i}/generate-video", headers=headers, json={
            "video_model": "gemini-2.0-flash-exp",
            "duration": 10,
            "resolution": "720p",
            "ratio": "9:16"
        })
        print(f"  Segment {i} ({SEGMENTS[i]['title']}): {r.status_code}")
        time.sleep(2)

    print(f"\nAll tasks submitted! Project ID: {pid}")
    print("Monitor progress at: http://122.51.205.94")

if __name__ == "__main__":
    main()
