<template>
  <div class="min-h-screen flex items-center justify-center relative overflow-hidden" style="background: var(--bg-canvas)">
    <!-- Static background generated by GPT-Image2 -->
    <img :src="themeStore.currentTheme.loginBg" class="absolute inset-0 w-full h-full object-cover opacity-30" alt="" style="filter: blur(2px);" />
    <!-- Theme-matched gradient overlay -->
    <div class="absolute inset-0" style="background: linear-gradient(to bottom, transparent 0%, var(--bg-canvas) 80%)"></div>

    <div class="relative z-10 w-full max-w-md px-4">
      <div class="glass-card p-8">
        <div class="text-center mb-8">
          <!-- Logo -->
          <div class="relative inline-flex items-center justify-center mb-4">
            <svg class="w-10 h-10" viewBox="0 0 32 32" fill="none" style="color: var(--accent)">
              <path d="M16 4L6 13l4 4-4 4 10 9 10-9-4-4 4-4-10-9z" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
              <circle cx="16" cy="16" r="2.5" fill="currentColor" opacity="0.6"/>
            </svg>
          </div>
          <h1 class="font-display text-2xl font-bold tracking-tight" style="color: var(--text-primary)">锻造</h1>
          <p class="text-sm mt-1" style="color: var(--text-secondary)">AI 创作平台</p>
        </div>

        <div class="space-y-4">
          <div class="flex rounded-xl overflow-hidden p-0.5" style="border: 1px solid var(--border-input)">
            <button
              @click="tab = 'login'"
              class="flex-1 py-2.5 text-sm font-medium rounded-lg transition-all duration-300"
              :style="tab === 'login' ? 'background: var(--accent); color: white' : 'color: var(--text-secondary)'"
            >登录</button>
            <button
              @click="tab = 'register'"
              class="flex-1 py-2.5 text-sm font-medium rounded-lg transition-all duration-300"
              :style="tab === 'register' ? 'background: var(--accent); color: white' : 'color: var(--text-secondary)'"
            >注册</button>
          </div>

          <div v-if="tab === 'login'">
            <input
              v-model="loginEmail"
              type="email"
              placeholder="邮箱"
              class="input-field mb-3"
              @keydown.enter="handleLogin"
            />
            <input
              v-model="loginPassword"
              type="password"
              placeholder="密码"
              class="input-field mb-4"
              @keydown.enter="handleLogin"
            />
            <button
              @click="handleLogin"
              :disabled="logging"
              class="btn-primary w-full text-sm py-2.5"
            >
              {{ logging ? '登录中...' : '登录' }}
            </button>
            <p v-if="loginError" class="text-xs mt-2 text-center" style="color: var(--color-error)">{{ loginError }}</p>
          </div>

          <div v-else>
            <input
              v-model="regEmail"
              type="email"
              placeholder="邮箱"
              class="input-field mb-3"
              @keydown.enter="handleRegister"
            />
            <input
              v-model="regPassword"
              type="password"
              placeholder="密码（至少6位）"
              class="input-field mb-3"
              @keydown.enter="handleRegister"
            />
            <input
              v-model="regNickname"
              type="text"
              placeholder="昵称（选填）"
              class="input-field mb-3"
              @keydown.enter="handleRegister"
            />
            <input
              v-model="regRefCode"
              type="text"
              placeholder="邀请码（选填）"
              class="input-field mb-4"
              @keydown.enter="handleRegister"
            />
            <button
              @click="handleRegister"
              :disabled="registering"
              class="btn-primary w-full text-sm py-2.5"
            >
              {{ registering ? '注册中...' : '注册' }}
            </button>
            <p v-if="regError" class="text-xs mt-2 text-center" style="color: var(--color-error)">{{ regError }}</p>
          </div>
        </div>
      </div>

      <p class="text-center text-xs mt-6" style="color: var(--text-muted)">
        登录即表示同意服务条款
      </p>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import { useThemeStore } from '@/stores/theme'

const router = useRouter()
const route = useRoute()
const auth = useAuthStore()
const themeStore = useThemeStore()

const refCode = (route.query.ref as string) || ''

const tab = ref<'login' | 'register'>('login')
const logging = ref(false)
const registering = ref(false)
const loginError = ref('')
const regError = ref('')

const loginEmail = ref('xiaye@aiforge.com')
const loginPassword = ref('zx4579561')
const regEmail = ref('')
const regPassword = ref('')
const regNickname = ref('')
const regRefCode = ref(refCode)

async function handleLogin() {
  if (!loginEmail.value || !loginPassword.value) return
  logging.value = true
  loginError.value = ''
  try {
    await auth.login(loginEmail.value, loginPassword.value)
    router.push({ name: 'workspace' })
  } catch (e: any) {
    loginError.value = e.message || '登录失败'
  } finally {
    logging.value = false
  }
}

async function handleRegister() {
  if (!regEmail.value || regPassword.value.length < 6) {
    regError.value = '请填写邮箱且密码至少6位'
    return
  }
  registering.value = true
  regError.value = ''
  try {
    await auth.register(regEmail.value, regPassword.value, regNickname.value, regRefCode.value)
    router.push({ name: 'workspace' })
  } catch (e: any) {
    regError.value = e.message || '注册失败'
  } finally {
    registering.value = false
  }
}
</script>
